---
include:
  - board: sofle_custom_left
    shield: nice_view_gem
  - board: sofle_custom_right
    shield: nice_view_gem
  - board: sofle_custom_left
    shield: nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: sofle_custom_studio_left
  - board: sofle_custom_left
    shield: settings_reset
