---
include:
  - board: nice_nano_v2
    shield: sofle_custom_left nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: sofle_custom_right nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: sofle_custom_left nice_view_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: sofle_custom_studio_left
  - board: nice_nano_v2
    shield: settings_reset
